'use client'

import Image from 'next/image'
import { useEffect, useState } from 'react'
import {
  ArrowLeft, ArrowRight, BadgeCheck, Bell, BellRing, CalendarDays, Check, ChevronRight,
  CircleDollarSign, Compass, CreditCard, FileCheck2, Gift, Heart, Home, LockKeyhole, Mail,
  MapPin, MessageCircle, MoreHorizontal, Plane, RefreshCw, ScanLine, Search, Send,
  ShieldCheck, SlidersHorizontal, Sparkles, Star, Target, TrendingUp, Trophy, Upload,
  WalletCards, X, CircleHelp, Zap
} from 'lucide-react'

type Tab = 'home'|'wallet'|'cira'|'travel'|'cards'|'menu'
type Detail = 'spend'|'flight-results'|'flight-decision'|'hotel-results'|'hotel-decision'|'card-detail'|'benefits'|'milestones'|'transfers'|'compare'|'switch'|'roast'|'statement'|'concierge'|'offers'|'profile'|'privacy'|'notifications'|'help'|null
type TravelMode = 'flights'|'hotels'|'dream'

const CARD_DATA = [
  {id:'infinia',bank:'HDFC',name:'Infinia Metal',art:'/card-art/hdfc-infinia.webp',points:'68,500',value:'₹68.5K'},
  {id:'atlas',bank:'Axis',name:'Atlas',art:'/card-art/axis-atlas.webp',points:'31,200',value:'₹42.1K'},
  {id:'amex',bank:'AmEx',name:'Platinum Travel',art:'/card-art/amex-platinum-travel.webp',points:'52,000',value:'₹39.0K'},
]
const ROUTES = [
  {code:'DEL',city:'Delhi',cash:'₹5,980',points:'3,200',airline:'IndiGo'},
  {code:'BOM',city:'Mumbai',cash:'₹4,650',points:'3,000',airline:'Air India'},
  {code:'GOI',city:'Goa',cash:'₹4,180',points:'2,800',airline:'Akasa Air'},
  {code:'HYD',city:'Hyderabad',cash:'₹3,690',points:'2,450',airline:'IndiGo'},
  {code:'MAA',city:'Chennai',cash:'₹3,420',points:'2,300',airline:'Air India Express'},
]
const STAYS = [
  {city:'Goa',hotel:'Taj Exotica Resort & Spa',cash:'₹18,000',points:'42,000',loyalty:'Taj / demo'},
  {city:'Mumbai',hotel:'ITC Maratha',cash:'₹16,500',points:'38,000',loyalty:'ITC / demo'},
  {city:'Delhi',hotel:'Andaz Delhi',cash:'₹14,200',points:'30,000',loyalty:'Hyatt / demo'},
  {city:'Bengaluru',hotel:'JW Marriott Bengaluru',cash:'₹15,800',points:'34,000',loyalty:'Marriott / demo'},
]

const DETAIL_COPY: Record<Exclude<Detail,null>, {kicker:string;title:string;rows:Array<[string,string]>;action?:string}> = {
  spend:{kicker:'SPEND SMART',title:'Get the best card for every spend.',rows:[]},
  'flight-results':{kicker:'DOMESTIC FLIGHTS',title:'BLR → DEL',rows:[]},
  'flight-decision':{kicker:'FLIGHT DECISION',title:'Pick the path that is actually executable.',rows:[]},
  'hotel-results':{kicker:'DOMESTIC STAYS',title:'Goa, India',rows:[]},
  'hotel-decision':{kicker:'STAY DECISION',title:'Cash or points? Make the trade-off obvious.',rows:[]},
  'card-detail':{kicker:'HDFC',title:'Infinia Metal',rows:[]},
  benefits:{kicker:'BENEFITS',title:'Use the perks you already paid for.',rows:[['Lounge access','2 visits tracked this quarter'],['Hotel benefit','Premium stay benefit available'],['Dining credit','1 benefit still unused'],['Renewal review','74 days until renewal']]},
  milestones:{kicker:'MILESTONES',title:'Chase only the milestones worth it.',rows:[['Axis Atlas','72% complete · ₹28K remaining'],['AmEx Platinum Travel','Milestone review in 18 days'],['HDFC Infinia','No forced spend recommendation']]},
  transfers:{kicker:'TRANSFER PARTNERS',title:'Know the route before moving points.',rows:[['KrisFlyer','Exact-card ratio verified in transfer graph'],['Air India Maharaja','Published programme guidance'],['Marriott Bonvoy','Projected until economics verified'],['Safety','Irreversible transfer requires explicit confirmation']]},
  compare:{kicker:'COMPARE',title:'Compare the capability, not just the annual fee.',rows:[['HDFC Infinia','Premium travel · strong reward flexibility'],['Axis Atlas','Transfer-focused · milestone structure'],['AmEx Platinum Travel','Milestone-led Membership Rewards']]},
  switch:{kicker:'SWITCH WIZARD',title:'Find cards that are not earning their keep.',rows:[['Card 1','Keep · benefits justify the fee'],['Card 2','Review · renewal in 32 days'],['Card 3','Possible downgrade · low benefit usage']]},
  roast:{kicker:'CARD ROAST',title:'Useful criticism, backed by the numbers.',rows:[['What it does well','Strong rewards in the right use case'],['Where it hurts','Annual fee needs active benefit usage'],['Who should avoid it','Low spend / low travel users']]},
  statement:{kicker:'STATEMENT TRUTH',title:'Turn statement lines into reward truth.',rows:[['Upload','PDF or image statement'],['Expected rewards','Compute from exact-card earn rules'],['Actual rewards','Compare against statement credits'],['Flags','Missed points, fees and anomalies']],action:'Upload demo statement'},
  concierge:{kicker:'CIRA CONCIERGE',title:'Hand off a decision without losing context.',rows:[['Travel brief','Route, cabin, wallet, cash fallback'],['Card brief','Current wallet and rationale'],['Safety','No sensitive card data'],['Status','Prototype request builder']],action:'Start concierge request'},
  offers:{kicker:'OFFERS & BENEFITS',title:'Only show offers that fit the wallet.',rows:[['Axis Atlas','Travel-category opportunity'],['HDFC Infinia','Premium merchant benefit'],['AmEx Platinum Travel','Milestone reminder']]},
  profile:{kicker:'MY ACCOUNT',title:'Your profile, preferences and travel style.',rows:[['Name','Goverdhan M D'],['Country','India'],['Currency','INR'],['Home airport','BLR · Bengaluru']]},
  privacy:{kicker:'PRIVACY & SECURITY',title:'Control every data surface.',rows:[['Biometrics','Enabled in production app design'],['Sensitive fields','Explicit reveal only'],['SMS access','Optional and revocable'],['Statements','User-initiated import only']]},
  notifications:{kicker:'SMART ALERTS',title:'Choose what deserves your attention.',rows:[['Point expiry','On'],['Annual fee review','On'],['Milestone deadline','On'],['Travel watch','On']]},
  help:{kicker:'HELP & FEEDBACK',title:'Correct data fast and keep trust high.',rows:[['Card data issue','Send exact field correction'],['Travel result issue','Flag source mismatch'],['Rewards question','Ask CIRA'],['Human support','Escalate when needed']]},
}

export function ReferenceApp(){
  const [ready,setReady]=useState(false)
  const [onboarded,setOnboarded]=useState(false)
  const [step,setStep]=useState(0)
  const [tab,setTab]=useState<Tab>('home')
  const [detail,setDetail]=useState<Detail>(null)
  const [alerts,setAlerts]=useState(false)
  useEffect(()=>{const p=new URLSearchParams(window.location.search);const review=p.get('review');if(review==='app')setOnboarded(true);else if(review==='setup')setOnboarded(false);else setOnboarded(localStorage.getItem('creditiq-reference-onboarded')==='1');setReady(true)},[])
  if(!ready)return <div className="ref-loading"/>
  const complete=()=>{localStorage.setItem('creditiq-reference-onboarded','1');setOnboarded(true);setStep(0)}
  const replay=()=>{localStorage.removeItem('creditiq-reference-onboarded');setOnboarded(false);setStep(0);setTab('home');setDetail(null)}
  const goTab=(t:Tab)=>{setTab(t);setDetail(null);setAlerts(false)}
  return <div className="ref-stage"><div className="ref-phone">{onboarded?<MainApp tab={tab} detail={detail} setDetail={setDetail} goTab={goTab} alerts={alerts} setAlerts={setAlerts} replay={replay}/>:<Setup step={step} setStep={setStep} complete={complete}/>}</div><div className="ref-desktop-note">Interactive prototype · reference-board visual parity · demo data unless labelled live</div></div>
}

function Setup({step,setStep,complete}:{step:number;setStep:(n:number)=>void;complete:()=>void}){
  const next=()=>setStep(Math.min(7,step+1));const back=()=>setStep(Math.max(0,step-1))
  return <div className={`ref-setup ref-setup-${step}`}>{step>0&&<div className="ref-setup-progress"><button onClick={back}><ArrowLeft/></button><div><span style={{width:`${Math.round(((step+1)/8)*100)}%`}}/></div><small>{step+1} of 8</small></div>}{step>0&&step<7&&<button className="ref-skip" onClick={complete}>Skip to app</button>}{step===0&&<Splash next={next} complete={complete}/>} {step===1&&<Story next={next}/>} {step===2&&<SignIn next={next}/>} {step===3&&<PrivacySetup next={next}/>} {step===4&&<AddCards next={next}/>} {step===5&&<Balances next={next}/>} {step===6&&<Goals next={next}/>} {step===7&&<FirstInsight complete={complete}/>}</div>
}
function Splash({next,complete}:{next:()=>void;complete:()=>void}){return <div className="ref-splash"><div className="ref-splash-photo"/><div className="ref-splash-ring"><span>Credit<span>IQ</span></span></div><div className="ref-splash-copy"><h1>Make every card<br/>work harder.</h1><p>Smarter cards. Brighter journeys.</p></div><div className="ref-splash-benefits"><div><Gift/><b>More rewards</b></div><div><Plane/><b>Better travel</b></div><div><TrendingUp/><b>Smarter spending</b></div><div><Sparkles/><b>A brighter you</b></div></div><div className="ref-splash-bottom"><span>INTELLIGENCE TURNS SPENDING INTO OPPORTUNITIES</span><button className="ref-gold-btn" onClick={next}>Get started <ArrowRight/></button><button className="ref-ghost-link" onClick={complete}>I already have an account</button></div></div>}
function Story({next}:{next:()=>void}){return <div className="ref-cream-screen ref-scrollable"><div className="ref-cream-head"><p className="ref-kicker">POINTS · REWARDS · TRAVEL</p><h2>Your wallet should tell you what to do next.</h2><p>Get best-card guidance, rewards intelligence and personalised insights — powered by CIRA.</p></div><div className="ref-story-visual"><div className="ref-story-sky"/><CardFan/><span className="ref-story-script">More than spending.</span></div><div className="ref-story-features"><div><Compass/><b>Right card</b><span>for every spend</span></div><div><Gift/><b>Maximise</b><span>rewards & cashback</span></div><div><Plane/><b>Turn points</b><span>into unforgettable trips</span></div></div><Bottom><button className="ref-dark-btn" onClick={next}>Next <ArrowRight/></button></Bottom></div>}
function SignIn({next}:{next:()=>void}){return <div className="ref-dark-screen ref-photo-top ref-scrollable"><div className="ref-sign-photo"/><div className="ref-overlay-copy"><Wordmark large/><h2>A smarter financial journey starts here.</h2><p>Sign in to unlock personalised insights with CIRA.</p></div><div className="ref-provider-stack"><button className="ref-provider white"><b className="google-dot">G</b>Continue with Google</button><button className="ref-provider">● Continue with Apple</button><button className="ref-provider"><Mail/>Continue with Email</button><div className="ref-or"><span/>OR<span/></div><label className="ref-input"><Mail/><input defaultValue="gogo@example.com"/></label><label className="ref-input"><LockKeyhole/><input defaultValue="••••••••"/></label><button className="ref-gold-btn" onClick={next}>Sign In <ArrowRight/></button></div></div>}
function PrivacySetup({next}:{next:()=>void}){return <div className="ref-dark-screen ref-scrollable ref-content-screen"><Header kicker="YOUR DATA. YOUR ADVANTAGE." title="Your privacy comes first." body="We only access what’s needed to give you smarter insights. You’re always in control."/><div className="ref-permission-list"><Toggle icon={BellRing} title="Notifications" text="Reward alerts and personalised tips."/><Toggle icon={MessageCircle} title="SMS Insights" text="Supported reward and spend messages."/><Toggle icon={Upload} title="Card Statements" text="Import statements when you choose."/><Toggle icon={ShieldCheck} title="Security Controls" text="Sensitive fields stay private."/></div><div className="ref-trust-card"><LockKeyhole/><div><b>Your trust powers a smarter you.</b><span>No bank password or full card number is requested.</span></div></div><Bottom><button className="ref-gold-btn" onClick={next}>Continue <ArrowRight/></button></Bottom></div>}
function AddCards({next}:{next:()=>void}){const[selected,setSelected]=useState(['infinia','atlas']);const toggle=(id:string)=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);return <div className="ref-dark-screen ref-scrollable ref-content-screen"><Header kicker="ADD YOUR CARDS" title="Connect the cards you already use." body="Search your card product. No full card number needed."/><label className="ref-input ref-search"><Search/><input placeholder="Search for your card"/></label><div className="ref-category-tabs"><button className="active">Popular</button><button>Travel</button><button>Cashback</button><button>Shopping</button></div><div className="ref-card-list">{CARD_DATA.map(c=><button className={`ref-card-row ${selected.includes(c.id)?'selected':''}`} key={c.id} onClick={()=>toggle(c.id)}><Image src={c.art} alt={c.name} width={110} height={70}/><div><b>{c.name}</b><span>{c.bank} · Premium rewards</span><small>Travel · Rewards · Benefits</small></div><em>{selected.includes(c.id)?<Check/>:<span>+ Add</span>}</em></button>)}</div><Bottom><button className="ref-gold-btn" onClick={next}>Add selected cards <ArrowRight/></button></Bottom></div>}
function Balances({next}:{next:()=>void}){return <div className="ref-cream-screen ref-scrollable ref-content-screen"><Header kicker="BRING IN YOUR DETAILS" title="Bring your existing card details." body="Let CIRA find your balances, spending and rewards — securely and privately."/><div className="ref-import-stack"><Import icon={MessageCircle} title="Scan SMS" text="Detect supported card spends and rewards."/><Import icon={Upload} title="Upload statement" text="Extract key card and reward details."/><Import icon={WalletCards} title="Enter manually" text="Add balances yourself."/></div><div className="ref-detected-card"><span>Detected for demo</span><div><b>3</b><small>cards found</small></div><div><b>151.7K</b><small>points tracked</small></div><div><b>₹1.50L</b><small>est. value</small></div></div><Bottom><button className="ref-gold-btn" onClick={next}>Continue <ArrowRight/></button></Bottom></div>}
function Goals({next}:{next:()=>void}){const[g,setG]=useState(['Travel better']);const defs=[['Travel better',Plane,'Maximise travel rewards and airport perks.'],['Earn more',TrendingUp,'Get higher rewards on everyday spend.'],['Save money',Gift,'Avoid unnecessary fees.'],['Simplify wallet',WalletCards,'Organise and track your cards.']] as const;return <div className="ref-dark-screen ref-scrollable ref-content-screen"><Header kicker="YOUR GOALS" title="What are your goals with CreditIQ?" body="Tell us what matters most. CIRA will personalise your insights."/><div className="ref-goal-grid">{defs.map(([title,Icon,text])=><button key={title} className={g.includes(title)?'selected':''} onClick={()=>setG(v=>v.includes(title)?v.filter(x=>x!==title):[...v,title])}><Icon/><b>{title}</b><span>{text}</span><i>{g.includes(title)?<Check/>:null}</i></button>)}</div><button className="ref-other-goal"><Target/>Any other goals?<ChevronRight/></button><Bottom><button className="ref-gold-btn" onClick={next}>Continue <ArrowRight/></button></Bottom></div>}
function FirstInsight({complete}:{complete:()=>void}){return <div className="ref-dark-screen ref-scrollable ref-content-screen ref-insight-screen"><div className="ref-cira-mini"><span><Sparkles/></span><div><b>Hi, I’m CIRA</b><small>I find opportunities your cards miss.</small></div></div><Header kicker="YOUR FIRST OPPORTUNITY" title="CIRA found your first opportunity." body="Here’s how you can get more from everyday spending."/><div className="ref-insight-card"><div className="ref-insight-merchant"><div className="merchant-logo">S</div><div><b>Swiggy</b><span>Food & Dining</span></div><strong>₹1,850</strong></div><div className="ref-insight-reco"><Image src="/card-art/axis-atlas.webp" alt="Axis Atlas" width={105} height={68}/><div><small>Recommended by CIRA</small><b>Use Axis Atlas</b><span>Projected value ₹185</span></div></div><div className="ref-insight-compare"><div><span>Your usual card</span><b>~₹23 value</b></div><div><span>With Atlas</span><b>~₹185 value</b></div></div><div className="ref-insight-upside"><TrendingUp/><span>You could get up to 5× more projected value.</span></div></div><Bottom><button className="ref-gold-btn" onClick={complete}>Open my CreditIQ <ArrowRight/></button></Bottom></div>}

function MainApp({tab,detail,setDetail,goTab,alerts,setAlerts,replay}:{tab:Tab;detail:Detail;setDetail:(d:Detail)=>void;goTab:(t:Tab)=>void;alerts:boolean;setAlerts:(v:boolean)=>void;replay:()=>void}){
  return <div className="ref-app"><header className="ref-app-header"><Wordmark/><div className="ref-app-title"><small>{detail?'CREDITIQ':tab==='home'?'GOOD MORNING, GOGO':'SMARTER CARDS. BRIGHTER JOURNEYS.'}</small><h1>{detail?DETAIL_COPY[detail].title:({home:'A brighter financial day.',wallet:'Your Wallet',cira:'CIRA',travel:'Travel',cards:'Cards',menu:'My Account'} as Record<Tab,string>)[tab]}</h1></div><button className="ref-round-icon" onClick={()=>setAlerts(!alerts)}><Bell/><i/></button></header>{detail&&<button className="ref-back" onClick={()=>setDetail(null)}><ArrowLeft/>Back</button>}{alerts&&<AlertBox close={()=>setAlerts(false)} setDetail={setDetail}/>}<main className="ref-main-scroll">{!detail&&tab==='home'&&<HomeScreen setDetail={setDetail} goTab={goTab}/>} {!detail&&tab==='wallet'&&<WalletScreen setDetail={setDetail}/>} {!detail&&tab==='cira'&&<Cira setDetail={setDetail}/>} {!detail&&tab==='travel'&&<Travel setDetail={setDetail}/>} {!detail&&tab==='cards'&&<Cards setDetail={setDetail}/>} {!detail&&tab==='menu'&&<Menu setDetail={setDetail} goTab={goTab} replay={replay}/>} {detail&&<DetailScreen detail={detail} setDetail={setDetail}/>}</main>{!detail&&<Nav tab={tab} goTab={goTab}/>}</div>
}
function HomeScreen({setDetail,goTab}:{setDetail:(d:Detail)=>void;goTab:(t:Tab)=>void}){return <div className="ref-stack"><section className="ref-home-hero"><div className="ref-home-photo"/><div className="ref-home-hero-copy"><span>BEST MOVE NOW</span><h2>You’re on track for a bigger tomorrow.</h2><p>Your wallet could earn <b>+28,400 pts</b> on upcoming spends.</p><button onClick={()=>setDetail('spend')}>See recommendation <ArrowRight/></button></div></section><div className="ref-home-duo"><button onClick={()=>goTab('travel')}><Plane/><div><span>BLR → DEL</span><b>Domestic travel ready</b></div><ChevronRight/></button><button onClick={()=>goTab('wallet')}><Trophy/><div><span>8,500 pts</span><b>expiring soon</b></div><ChevronRight/></button></div><Section title="For you today"/><Feed photo="travel" title="Use your wallet smarter on domestic trips" text="Compare cash and points before booking." onClick={()=>goTab('travel')}/><Feed photo="spend" title="You can save more on your next online spend" text="Check your best exact card before you pay." onClick={()=>setDetail('spend')}/><div className="ref-quick-grid"><Quick icon={ScanLine} title="Spend Smart" text="Best card now" onClick={()=>setDetail('spend')}/><Quick icon={Sparkles} title="Ask CIRA" text="Plan anything" onClick={()=>goTab('cira')}/><Quick icon={Gift} title="Offers" text="Wallet-relevant" onClick={()=>setDetail('offers')}/><Quick icon={FileCheck2} title="Statement Truth" text="Verify rewards" onClick={()=>setDetail('statement')}/></div></div>}
function WalletScreen({setDetail}:{setDetail:(d:Detail)=>void}){const[i,setI]=useState(0);const c=CARD_DATA[i];return <div className="ref-stack"><section className="ref-wallet-card-stack"><div className="ref-card-shadow left"><Image src={CARD_DATA[2].art} alt="AmEx" width={126} height={80}/></div><button className="ref-wallet-main-card" onClick={()=>setDetail('card-detail')}><Image src={c.art} alt={c.name} width={240} height={150}/></button><div className="ref-card-shadow right"><Image src={CARD_DATA[1].art} alt="Axis" width={126} height={80}/></div><div className="ref-carousel-dots">{CARD_DATA.map((_,n)=><button key={n} className={i===n?'active':''} onClick={()=>setI(n)}/>)}</div></section><section className="ref-wallet-total"><div><span>Total tracked value</span><b>₹1,49,600</b><small>151,700 points across 3 cards</small></div><div className="ref-growth">↗ 18%<span>demo</span></div></section><Metrics/><section className="ref-wallet-iq"><div><Sparkles/><span><b>Wallet IQ · 87</b><small>You may be underusing one premium benefit.</small></span><ChevronRight/></div></section><div className="ref-subtabs"><button className="active">Balances</button><button onClick={()=>setDetail('benefits')}>Benefits</button><button onClick={()=>setDetail('milestones')}>Milestones</button><button onClick={()=>setDetail('transfers')}>Transfers</button></div><div className="ref-balance-list">{CARD_DATA.map(x=><button key={x.id} onClick={()=>setDetail('card-detail')}><Image src={x.art} alt={x.name} width={58} height={38}/><div><b>{x.name}</b><span>{x.bank} rewards</span></div><strong>{x.points} pts</strong></button>)}</div></div>}
function Cira({setDetail}:{setDetail:(d:Detail)=>void}){const[draft,setDraft]=useState('');const[msg,setMsg]=useState<string[]>([]);const send=(t=draft)=>{if(!t.trim())return;setMsg(v=>[...v,t.trim()]);setDraft('')};return <div className="ref-cira-screen"><div className="ref-cira-orb"><span><Sparkles/></span></div><p className="ref-cira-sub">Your personal card & travel intelligence</p><h2>Ask. Plan. Go further.</h2><p>CIRA helps you make every spend, trip and card decision more rewarding.</p><div className="ref-cira-chips">{['Best card for ₹25K?','Plan BLR → DEL','Maximise my points','Lounge access options'].map(x=><button key={x} onClick={()=>send(x)}>{x}</button>)}</div><div className="ref-chat-area">{msg.map((m,i)=><div key={i}><div className="user">{m}</div><div className="bot"><b>CIRA</b><span>I’ll compare exact card rules, wallet balance, source authority and executable paths first.</span></div></div>)}</div><div className="ref-cira-actions"><button onClick={()=>setDetail('spend')}>Check a spend</button><button onClick={()=>setDetail('concierge')}>Concierge</button></div><div className="ref-chat-input"><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Ask CIRA anything…"/><button onClick={()=>send()}><Send/></button></div></div>}
function Travel({setDetail}:{setDetail:(d:Detail)=>void}){const[mode,setMode]=useState<TravelMode>('flights');const[to,setTo]=useState('DEL');const[city,setCity]=useState('Goa');const route=ROUTES.find(r=>r.code===to)||ROUTES[0];return <div className="ref-stack"><div className="ref-segment"><button className={mode==='flights'?'active':''} onClick={()=>setMode('flights')}>Flights</button><button className={mode==='hotels'?'active':''} onClick={()=>setMode('hotels')}>Hotels</button><button className={mode==='dream'?'active':''} onClick={()=>setMode('dream')}>Dream Trip</button></div>{mode==='flights'&&<><TravelHero kind="flight" kicker="INDIA-FIRST SEARCH" title="Smarter ways to get there." text="Compare cash and points for domestic routes."/><section className="ref-route-box"><div><small>FROM</small><b>BLR</b><span>Bengaluru</span></div><Plane/><div><small>TO</small><b>{route.code}</b><span>{route.city}</span></div></section><div className="ref-destination-pills">{ROUTES.map(r=><button key={r.code} className={to===r.code?'active':''} onClick={()=>setTo(r.code)}>{r.code}</button>)}</div><div className="ref-travel-options"><button><CalendarDays/>20 Sep</button><button>Economy</button><button>1 adult</button></div><button className="ref-gold-btn" onClick={()=>setDetail('flight-results')}>Search domestic flights <Search/></button></>}{mode==='hotels'&&<><TravelHero kind="hotel" kicker="DOMESTIC STAYS" title="Extraordinary stays. Smarter choices." text="Compare cash, points and loyalty paths."/><label className="ref-input"><MapPin/><input value={city} onChange={e=>setCity(e.target.value)}/></label><div className="ref-destination-pills">{STAYS.map(h=><button key={h.city} className={city===h.city?'active':''} onClick={()=>setCity(h.city)}>{h.city}</button>)}</div><button className="ref-gold-btn" onClick={()=>setDetail('hotel-results')}>Search domestic stays <Search/></button></>}{mode==='dream'&&<section className="ref-dream-card"><div className="ref-cira-orb small"><span><Sparkles/></span></div><span>DREAM TRIP</span><h2>“Take me to Rajasthan for 5 nights using my points.”</h2><p>CIRA builds flights, stays and fallback cash options around your wallet.</p><button className="ref-gold-btn">Build my trip <ArrowRight/></button></section>}</div>}
function Cards({setDetail}:{setDetail:(d:Detail)=>void}){return <div className="ref-stack"><section className="ref-cards-intro"><span>NEXT CARD</span><h2>Find your next card.</h2><p>Personalised recommendations based on your wallet, spending and goals.</p></section><div className="ref-subtabs"><button className="active">Recommended</button><button>Travel</button><button>Cashback</button><button>Luxury</button></div><section className="ref-reco-card"><div className="ref-fit-ring"><b>92</b><span>fit</span></div><Image src="/card-art/hdfc-infinia.webp" alt="HDFC Infinia" width={150} height={96}/><div><span>BEST FOR YOU</span><h3>HDFC Infinia</h3><p>Premium travel. Elevated everyday value.</p></div><div className="ref-reco-feature-grid"><span><Plane/>Strong travel</span><span><Star/>Premium benefits</span><span><Gift/>Reward flexibility</span><span><BadgeCheck/>Low overlap</span></div><div className="ref-dual-actions"><button onClick={()=>setDetail('compare')}>Compare</button><button className="gold" onClick={()=>setDetail('card-detail')}>View details</button></div></section><div className="ref-quick-grid"><Quick icon={RefreshCw} title="Switch Wizard" text="Fix weak cards" onClick={()=>setDetail('switch')}/><Quick icon={Zap} title="Card Roast" text="Evidence, with attitude" onClick={()=>setDetail('roast')}/></div></div>}
function Menu({setDetail,goTab,replay}:{setDetail:(d:Detail)=>void;goTab:(t:Tab)=>void;replay:()=>void}){return <div className="ref-stack"><section className="ref-profile-card"><div className="ref-avatar">G</div><div><b>Goverdhan M D</b><span>CreditIQ Pro · India</span></div><button onClick={()=>setDetail('profile')}><ChevronRight/></button></section><button className="ref-concierge-banner" onClick={()=>setDetail('concierge')}><div className="ref-cira-orb tiny"><span><Sparkles/></span></div><div><b>CIRA Concierge</b><span>Always on your side.</span></div><em>Chat now</em></button><div className="ref-menu-list"><MenuRow icon={FileCheck2} title="Statement Truth" text="Turn statements into insights" onClick={()=>setDetail('statement')}/><MenuRow icon={Gift} title="Offers & Benefits" text="Curated for your cards" onClick={()=>setDetail('offers')}/><MenuRow icon={WalletCards} title="My Connected Wallet" text="Cards, points and loyalty" onClick={()=>goTab('wallet')}/><MenuRow icon={ShieldCheck} title="Privacy & Security" text="Your data stays private" onClick={()=>setDetail('privacy')}/><MenuRow icon={Bell} title="Notifications" text="Alerts and opportunities" onClick={()=>setDetail('notifications')}/><MenuRow icon={CircleHelp} title="Help & Feedback" text="Support and corrections" onClick={()=>setDetail('help')}/><MenuRow icon={RefreshCw} title="Replay Onboarding" text="Take the tour again" onClick={replay}/></div></div>}

function DetailScreen({detail,setDetail}:{detail:Exclude<Detail,null>;setDetail:(d:Detail)=>void}){if(detail==='spend')return <Spend/>;if(detail==='flight-results')return <FlightResults setDetail={setDetail}/>;if(detail==='flight-decision')return <FlightDecision/>;if(detail==='hotel-results')return <HotelResults setDetail={setDetail}/>;if(detail==='hotel-decision')return <HotelDecision/>;if(detail==='card-detail')return <CardDetail setDetail={setDetail}/>;const c=DETAIL_COPY[detail];return <Generic kicker={c.kicker} title={c.title} rows={c.rows} action={c.action}/>}
function Spend(){const[merchant,setMerchant]=useState('Starbucks');const[amount,setAmount]=useState('1200');return <div className="ref-stack ref-detail-screen"><div className="ref-segment"><button className="active">Single purchase</button><button>Monthly spend</button><button>Travel booking</button></div><section className="ref-form-panel"><label><span>Where are you spending?</span><div className="ref-input"><MapPin/><input value={merchant} onChange={e=>setMerchant(e.target.value)}/></div></label><label><span>Enter amount</span><div className="ref-input"><CircleDollarSign/><input value={amount} onChange={e=>setAmount(e.target.value)}/></div></label><button className="ref-gold-btn">Find best card <ArrowRight/></button></section><Section title="Best card for this spend"/><Recommendation primary/><Section title="Second best option"/><Recommendation/><div className="ref-explain-box"><b>Why this card?</b><span><Check/>Highest projected value for this merchant</span><span><Check/>Exact-card rules, no bank-level inheritance</span><span><Check/>Milestone timing included where known</span></div></div>}
function FlightResults({setDetail}:{setDetail:(d:Detail)=>void}){return <div className="ref-stack ref-detail-screen"><div className="ref-route-result-head"><div><b>BLR → DEL</b><span>20 Sep · 1 adult · Economy</span></div><button><SlidersHorizontal/></button></div><div className="ref-subtabs"><button className="active">Best options</button><button>Cash</button><button>Points</button><button>Fastest</button></div><div className="ref-status-good"><BadgeCheck/>Demo route cards below. Live provider verification is required before investor use.</div>{ROUTES.slice(0,4).map((r,i)=><button className="ref-flight-row" key={r.code} onClick={()=>setDetail('flight-decision')}><div className={`airline-dot a${i}`}>{i===0?'6E':i===1?'AI':i===2?'QP':'IX'}</div><div><b>{r.airline}</b><span>08:00 – 10:45 · nonstop</span></div><div><strong>{r.cash}</strong><em>{r.points} pts</em></div><ChevronRight/></button>)}</div>}
function FlightDecision(){return <div className="ref-stack ref-detail-screen"><section className="ref-decision-hero"><span>BLR → DEL · INDIGO</span><h2>Pick the path that is actually executable.</h2><p>Cash and points stay separated until availability and wallet requirements are confirmed.</p></section><Decision title="Cash price" value="₹5,980" text="Demo fare · live verification required"/><Decision title="Points option" value="3,200 pts + taxes unknown" text="Projected only · award availability must be verified"/><div className="ref-value-callout"><BadgeCheck/><div><b>Investor-demo rule</b><span>Do not label this bookable until the domestic provider gate is green.</span></div></div></div>}
function HotelResults({setDetail}:{setDetail:(d:Detail)=>void}){return <div className="ref-stack ref-detail-screen"><div className="ref-route-result-head"><div><b>Goa, India</b><span>20–24 Sep · 2 guests</span></div><button><SlidersHorizontal/></button></div><div className="ref-subtabs"><button className="active">Popular</button><button>Price</button><button>Points</button><button>Rating</button></div>{STAYS.map((h,i)=><button className="ref-hotel-row" key={h.hotel} onClick={()=>setDetail('hotel-decision')}><div className={`ref-hotel-thumb h${i}`}/><div><b>{h.hotel}</b><span>{h.city} · {h.loyalty}</span><small>Demo stay · verify live availability</small></div><div><strong>{h.cash}</strong><em>{h.points} pts</em></div><Heart/></button>)}</div>}
function HotelDecision(){return <div className="ref-stack ref-detail-screen"><section className="ref-hotel-decision-photo"/><Header kicker="TAJ EXOTICA RESORT & SPA" title="Cash or points? Make the trade-off obvious." body="Projected loyalty value stays separate from a verified bookable rate."/><Decision title="Cash path" value="₹72,000" text="4 nights · demo total"/><Decision title="Points path" value="168,000 points" text="Projected demo only · confirm live inventory"/></div>}
function CardDetail({setDetail}:{setDetail:(d:Detail)=>void}){return <div className="ref-stack ref-detail-screen"><section className="ref-card-detail-hero"><Image src="/card-art/hdfc-infinia.webp" alt="HDFC Infinia" width={250} height={160}/><span>HDFC</span><h2>Infinia Metal</h2><p>Premium travel · exact-card rewards intelligence</p></section><Metrics/><div className="ref-quick-grid"><Quick icon={Gift} title="Benefits" text="5 tracked" onClick={()=>setDetail('benefits')}/><Quick icon={Trophy} title="Milestones" text="2 active" onClick={()=>setDetail('milestones')}/><Quick icon={Plane} title="Transfers" text="6 paths" onClick={()=>setDetail('transfers')}/><Quick icon={BadgeCheck} title="Verify" text="1 item"/></div></div>}

function Generic({kicker,title,rows,action}:{kicker:string;title:string;rows:Array<[string,string]>;action?:string}){return <div className="ref-stack ref-detail-screen"><Header kicker={kicker} title={title} body="Reference-board visual system · financial values remain demo unless explicitly verified live."/><div className="ref-generic-list">{rows.map(([a,b])=><div key={a}><b>{a}</b><span>{b}</span><ChevronRight/></div>)}</div>{action&&<button className="ref-gold-btn">{action}<ArrowRight/></button>}</div>}
function AlertBox({close,setDetail}:{close:()=>void;setDetail:(d:Detail)=>void}){return <div className="ref-alert-panel"><div><b>Smart alerts</b><button onClick={close}><X/></button></div><button onClick={()=>setDetail('milestones')}><Trophy/><span><b>Atlas milestone</b><small>18 days left</small></span></button><button onClick={()=>setDetail('benefits')}><Gift/><span><b>Benefit expiring</b><small>Review before renewal</small></span></button><button onClick={()=>setDetail('flight-results')}><Plane/><span><b>Domestic route watch</b><small>Needs live provider verification</small></span></button></div>}
function Nav({tab,goTab}:{tab:Tab;goTab:(t:Tab)=>void}){const n=[[Home,'home','Home'],[WalletCards,'wallet','Wallet'],[Sparkles,'cira','CIRA'],[Plane,'travel','Travel'],[CreditCard,'cards','Cards'],[MoreHorizontal,'menu','Menu']] as const;return <nav className="ref-bottom-nav">{n.map(([Icon,id,label])=><button key={id} className={`${tab===id?'active':''} ${id==='cira'?'cira':''}`} onClick={()=>goTab(id)}><span><Icon/></span><small>{label}</small></button>)}</nav>}
function Bottom({children}:{children:React.ReactNode}){return <div className="ref-bottom-pad">{children}</div>}
function Wordmark({large=false}:{large?:boolean}){return <div className={`ref-wordmark ${large?'large':''}`}>Credit<span>IQ</span></div>}
function Header({kicker,title,body}:{kicker:string;title:string;body:string}){return <div className="ref-header-copy"><p>{kicker}</p><h2>{title}</h2><span>{body}</span></div>}
function Toggle({icon:Icon,title,text}:{icon:any;title:string;text:string}){const[on,setOn]=useState(true);return <button className="ref-toggle-row" onClick={()=>setOn(!on)}><span><Icon/></span><div><b>{title}</b><small>{text}</small></div><i className={on?'on':''}><em/></i></button>}
function Import({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <button className="ref-import-row"><span><Icon/></span><div><b>{title}</b><small>{text}</small></div><ChevronRight/></button>}
function CardFan(){return <div className="ref-card-fan"><Image className="fan-a" src="/card-art/hdfc-infinia.webp" alt="Infinia" width={180} height={115}/><Image className="fan-b" src="/card-art/axis-atlas.webp" alt="Atlas" width={180} height={115}/><Image className="fan-c" src="/card-art/amex-platinum-travel.webp" alt="AmEx" width={180} height={115}/></div>}
function Section({title}:{title:string}){return <div className="ref-section-title"><h3>{title}</h3></div>}
function Feed({photo,title,text,onClick}:{photo:string;title:string;text:string;onClick:()=>void}){return <button className="ref-feed-media" onClick={onClick}><div className={`ref-feed-image ${photo}`}/><div><small>FOR YOU</small><b>{title}</b><span>{text}</span></div><ChevronRight/></button>}
function Quick({icon:Icon,title,text,onClick}:{icon:any;title:string;text:string;onClick?:()=>void}){return <button onClick={onClick}><Icon/><b>{title}</b><span>{text}</span></button>}
function Metrics(){return <div className="ref-wallet-metrics"><div><b>151.7K</b><span>Total points</span></div><div><b>₹1.50L</b><span>Est. value</span></div><div><b>3</b><span>Active cards</span></div><div><b>12</b><span>Partners</span></div></div>}
function Recommendation({primary=false}:{primary?:boolean}){return <button className={`ref-recommendation ${primary?'primary':''}`}><Image src={primary?'/card-art/hdfc-infinia.webp':'/card-art/amex-platinum-travel.webp'} alt={primary?'HDFC Infinia':'AmEx Platinum Travel'} width={92} height={58}/><div><small>{primary?'RECOMMENDED':'SECOND BEST'}</small><b>{primary?'HDFC Infinia':'AmEx Platinum Travel'}</b><span>{primary?'Earn 720 points · projected value ₹360':'Earn 480 points · projected value ₹240'}</span></div><ChevronRight/></button>}
function TravelHero({kind,kicker,title,text}:{kind:'flight'|'hotel';kicker:string;title:string;text:string}){return <section className={`ref-travel-hero ${kind}`}><div className={`ref-travel-photo ${kind}`}/><div className="ref-travel-copy"><span>{kicker}</span><h2>{title}</h2><p>{text}</p></div></section>}
function Decision({title,value,text}:{title:string;value:string;text:string}){return <section className="ref-decision-option"><div><span>{title}</span><b>{value}</b><small>{text}</small></div><button>Select</button></section>}
function MenuRow({icon:Icon,title,text,onClick}:{icon:any;title:string;text:string;onClick:()=>void}){return <button onClick={onClick}><Icon/><div><b>{title}</b><span>{text}</span></div><ChevronRight/></button>}
