// AUTO-GENERATED by scripts/gen-card-art-manifest.ts — do not edit by hand.
//
// Lists the SEED_CARDS slugs that have a self-hosted card face at
// public/cards/<slug>.webp. <CardArt> renders that image when the slug is
// present here, and falls back to the CSS card tile (CardMockup / CreditCard3D)
// otherwise.
//
// Re-run `npm run gen:card-art` after changing files in public/cards/.
export const CARD_ART_SLUGS: ReadonlySet<string> = new Set<string>([
  'amex-gold',
  'amex-mrcc',
  'amex-platinum-travel',
  'axis-atlas',
  'hdfc-diners-black',
  'hdfc-infinia',
  'hdfc-marriott-bonvoy',
  'hdfc-millennia',
  'hdfc-regalia-gold',
  'hdfc-swiggy',
  'icici-amazon-pay',
  'sbi-cashback',
  'sbi-elite',
  'tata-neu-infinity-hdfc',
]);

/** True when a self-hosted face exists for this slug. */
export function hasCardArt(slug: string): boolean {
  return CARD_ART_SLUGS.has(slug);
}

/** Public path to a card's self-hosted face. Only valid when hasCardArt(slug). */
export function cardArtSrc(slug: string): string {
  return `/cards/${slug}.webp`;
}
