/**
 * gen-card-art-manifest.ts — regenerates lib/data/card-art-manifest.ts.
 *
 * Scans public/cards/ for `<slug>.webp` faces and writes the set of slugs that
 * have art. <CardArt> reads this to decide image-vs-CSS-fallback per card.
 *
 * Run: `npm run gen:card-art` (or `tsx scripts/gen-card-art-manifest.ts`).
 * Run it whenever you add/remove files in public/cards/. With no images present
 * it writes an empty set, which is the correct state for commit (a).
 *
 * It also warns about `<slug>.webp` files whose slug is not a real SEED_CARDS id
 * (a typo'd filename would otherwise silently never render).
 */
import { existsSync, readdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { SEED_CARDS } from '../lib/data/seed-cards';

const CARDS_DIR = join('public', 'cards');
const OUT = join('lib', 'data', 'card-art-manifest.ts');

const validSlugs = new Set(SEED_CARDS.map((c) => c.slug));

const slugs = existsSync(CARDS_DIR)
  ? readdirSync(CARDS_DIR)
      .filter((f) => f.toLowerCase().endsWith('.webp'))
      .map((f) => f.replace(/\.webp$/i, ''))
      .sort()
  : [];

const orphans = slugs.filter((s) => !validSlugs.has(s));
if (orphans.length) {
  console.warn(`⚠ gen-card-art: ${orphans.length} file(s) in public/cards/ have no matching SEED_CARDS slug (won't render): ${orphans.join(', ')}`);
}

const list = slugs.map((s) => `  '${s}',`).join('\n');
const body = `// AUTO-GENERATED by scripts/gen-card-art-manifest.ts — do not edit by hand.
//
// Lists the SEED_CARDS slugs that have a self-hosted card face at
// public/cards/<slug>.webp. <CardArt> renders that image when the slug is
// present here, and falls back to the CSS card tile (CardMockup / CreditCard3D)
// otherwise.
//
// Re-run \`npm run gen:card-art\` after changing files in public/cards/.
export const CARD_ART_SLUGS: ReadonlySet<string> = new Set<string>([${slugs.length ? `\n${list}\n` : ''}]);

/** True when a self-hosted face exists for this slug. */
export function hasCardArt(slug: string): boolean {
  return CARD_ART_SLUGS.has(slug);
}

/** Public path to a card's self-hosted face. Only valid when hasCardArt(slug). */
export function cardArtSrc(slug: string): string {
  return \`/cards/\${slug}.webp\`;
}
`;

writeFileSync(OUT, body, { encoding: 'utf8' });
console.log(`✓ gen-card-art: wrote ${OUT} with ${slugs.length} card face(s).`);
